services:
  - type: web
    name: usdt-arbitrage-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python usdt_arbitrage_web.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: your_bot_token
      - key: TELEGRAM_CHAT_ID
        value: your_chat_id
      - key: ARBITRAGE_SYMBOL
        value: BTC/USDT
      - key: ARBITRAGE_THRESHOLD
        value: 2.0
